#!/usr/bin/env python3
"""Move a consumer's instruction files into AGENTS.md, losing nothing.

Template v0.5.0 retires CLAUDE.md: AGENTS.md is the one instruction file, read by
Claude Code natively (2.1.277+), Codex and OpenCode. This helper moves the
consumer's OWN text out of the retiring files and into AGENTS.md, below the
template-managed region, then deletes each source — but only after proving the
move lost nothing.

    migrate-instructions.py --agents AGENTS.md --template-lines FILE SRC [SRC ...]

For each SRC (a path relative to the repo root, e.g. CLAUDE.md, .claude/CLAUDE.md,
.claude/rules/project-conventions.md):

  1. Split it into sections at markdown headings, ignoring anything that looks
     like a heading inside a fenced code block.
  2. Drop a section only when EVERY non-blank line in it is a line the template
     has shipped at some point (TEMPLATE_LINES, built from git history). Such a
     section is template boilerplate the consumer never touched.
  3. Keep every other section byte-for-byte, minus `@AGENTS.md` import lines
     (AGENTS.md must not import itself). Relative markdown links and `@path`
     imports are re-based from the source's directory to the repo root, because
     the text moves; each rewrite is reported.
  4. Append the kept text to AGENTS.md under a one-line provenance comment.
  5. CONSERVATION CHECK: every non-blank source line that is not a template line
     must now appear, after the reported rewrite, as a line of AGENTS.md. If any
     is missing, AGENTS.md is restored and the source is KEPT. Only a passing
     check deletes the source.

Output: one line per event, tab-separated, for upgrade.sh/init.sh to report:
  MOVED  <src>  <n foreign lines>      TEMPLATE-ONLY  <src>
  KEPT   <src>  <reason>               REWROTE <src> <old> -> <new>
  UNRESOLVED <src> <link>   (relative link whose target does not exist)
Exit status is 0 unless a source had to be kept because the check failed.

    migrate-instructions.py --check-conservation --template-lines FILE --agents AGENTS.md ORIG...
re-runs only the check against ORIGINAL copies (e.g. from a backup): it is the
same predicate the tests and canaries use, so a parser bug cannot pass quietly.
"""
import argparse
import os
import re
import sys

FENCE = re.compile(r"^\s*(```|~~~)")
HEADING = re.compile(r"^#{1,6}\s")
LINK = re.compile(r"(\]\()([^)\s]+)(\))")          # [text](target)
IMPORT = re.compile(r"(^|\s)@([^\s`]+)")            # @path/to/file.md
MARK = "<!-- moved here from {src} by agentic-repo-template v0.5.0 -->"


def norm(line):
    return line.rstrip()


def load_template_lines(path):
    with open(path, encoding="utf-8") as fh:
        return {norm(l) for l in fh if l.strip() and not l.startswith("# Generated by")
                and not l.startswith("# template has ever") and not l.startswith("# as the consumer")}


def sections(text):
    """Split into sections at headings outside fenced code blocks."""
    out, cur, in_fence = [], [], False
    for line in text.splitlines(keepends=True):
        if FENCE.match(line):
            in_fence = not in_fence
        elif not in_fence and HEADING.match(line) and cur:
            out.append(cur)
            cur = []
        cur.append(line)
    if cur:
        out.append(cur)
    return out


def is_import_of_agents(line):
    return norm(line).strip() == "@AGENTS.md"


def rebase(target, src_dir, root):
    """Re-base a relative target from src_dir to the repo root, or None to leave it."""
    if (not target or target.startswith(("/", "#", "~", "$")) or re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", target)
            or src_dir in ("", ".")):
        return None
    path, _, frag = target.partition("#")
    if not path:
        return None
    new = os.path.normpath(os.path.join(src_dir, path))
    if frag:
        new += "#" + frag
    return new


def migrate_line(line, src, src_dir, root, events):
    """Apply link/import re-basing to one kept line; report each rewrite."""
    def fix_link(m):
        new = rebase(m.group(2), src_dir, root)
        if new is None or new == m.group(2):
            return m.group(0)
        if not os.path.exists(os.path.join(root, new.partition("#")[0])):
            events.append(("UNRESOLVED", src, m.group(2)))
        events.append(("REWROTE", src, f"{m.group(2)} -> {new}"))
        return m.group(1) + new + m.group(3)

    def fix_import(m):
        tgt = m.group(2)
        if tgt == "AGENTS.md" or "@" in tgt or "." not in os.path.basename(tgt):
            return m.group(0)                      # not a file import (e.g. an email, a handle)
        new = rebase(tgt, src_dir, root)
        if new is None or new == tgt:
            return m.group(0)
        if not os.path.exists(os.path.join(root, new)):
            events.append(("UNRESOLVED", src, "@" + tgt))
        events.append(("REWROTE", src, f"@{tgt} -> @{new}"))
        return m.group(1) + "@" + new

    return IMPORT.sub(fix_import, LINK.sub(fix_link, line))


def plan(src, root, tlines, events):
    """Return (kept_text, expected_foreign_lines) for one source."""
    with open(os.path.join(root, src), encoding="utf-8") as fh:
        text = fh.read()
    src_dir = os.path.dirname(src)
    kept, expected = [], []
    for sec in sections(text):
        body = [l for l in sec if l.strip()]
        if all(norm(l) in tlines for l in body):
            continue                                   # untouched template boilerplate
        for line in sec:
            if is_import_of_agents(line):
                continue
            new = migrate_line(line, src, src_dir, root, events)
            kept.append(new)
            if line.strip() and norm(line) not in tlines:
                expected.append(norm(new))
    return "".join(kept), expected


def agents_lines(path):
    with open(path, encoding="utf-8") as fh:
        return {norm(l) for l in fh}


def migrate(args):
    root = os.getcwd()
    tlines = load_template_lines(args.template_lines)
    failed = False
    if os.path.islink(args.agents):
        # `ln -s AGENTS.md CLAUDE.md` (or the reverse) is a documented setup: deleting
        # one side would destroy the corpus. Touch nothing; say why.
        print(f"KEPT\t*\t{args.agents} is a symlink — migrate by hand")
        return 1
    for src in args.sources:
        path = os.path.join(root, src)
        if os.path.islink(path):
            # `ln -s AGENTS.md CLAUDE.md` is Anthropic's documented workaround: the
            # link carries no text of its own, so removing it loses nothing. A link
            # to anything else is the consumer's arrangement — keep it.
            if os.path.realpath(path) == os.path.realpath(args.agents):
                os.remove(path)
                print(f"LINK-REMOVED\t{src}")
            else:
                print(f"KEPT\t{src}\tis a symlink to {os.readlink(path)} — not moved")
                failed = True
            continue
        if not os.path.isfile(path):
            continue
        events = []
        kept, expected = plan(src, root, tlines, events)
        if not kept.strip():
            os.remove(os.path.join(root, src))
            print(f"TEMPLATE-ONLY\t{src}")
            continue
        with open(args.agents, encoding="utf-8") as fh:
            before = fh.read()
        block = ("" if before.endswith("\n\n") else ("\n" if before.endswith("\n") else "\n\n")) \
            + MARK.format(src=src) + "\n" + kept + ("" if kept.endswith("\n") else "\n")
        with open(args.agents, "a", encoding="utf-8") as fh:
            fh.write(block)
        # Check against the bytes this call appended, read back from disk — not the
        # whole file, where a line that already exists elsewhere would pass unwritten.
        with open(args.agents, encoding="utf-8") as fh:
            after = fh.read()
        written = {norm(l) for l in after[len(before):].splitlines()} if after.startswith(before) else set()
        missing = [l for l in expected if l not in written]
        if missing:
            with open(args.agents, "w", encoding="utf-8") as fh:
                fh.write(before)                       # undo: nothing half-moved
            print(f"KEPT\t{src}\tconservation check failed on {len(missing)} line(s), e.g. {missing[0][:80]!r}")
            failed = True
            continue
        for e in events:
            print("\t".join(e))
        os.remove(os.path.join(root, src))
        print(f"MOVED\t{src}\t{len(expected)}")
    return 1 if failed else 0


def check(args):
    """Same predicate, against original copies: every foreign line is in AGENTS.md."""
    tlines = load_template_lines(args.template_lines)
    have = agents_lines(args.agents)
    root = os.getcwd()
    bad = 0
    for spec in args.sources:
        # ORIG=REPO_PATH: an original copy, re-based as if it lived at REPO_PATH.
        orig, _, repo_path = spec.partition("=")
        label = repo_path or orig
        src_dir = os.path.dirname(repo_path)
        with open(orig, encoding="utf-8") as fh:
            text = fh.read()
        in_managed = False
        for line in text.splitlines():
            # Lines inside a template-managed fence are the template's own text and
            # are REPLACED by design on upgrade; conservation concerns only what
            # the consumer wrote, i.e. everything outside the fence.
            if "BEGIN template-managed" in line:
                in_managed = True
                continue
            if "END template-managed" in line:
                in_managed = False
                continue
            if in_managed or not line.strip() or norm(line) in tlines or is_import_of_agents(line):
                continue
            want = norm(migrate_line(line, label, src_dir, root, []))
            if want not in have:
                print(f"LOST\t{label}\t{want[:100]}")
                bad += 1
    print(f"conservation: {'PASS' if not bad else 'FAIL'} ({bad} line(s) missing)")
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--agents", required=True)
    ap.add_argument("--template-lines", required=True)
    ap.add_argument("--check-conservation", action="store_true")
    ap.add_argument("sources", nargs="+")
    args = ap.parse_args()
    return check(args) if args.check_conservation else migrate(args)


if __name__ == "__main__":
    sys.exit(main())
